import {
  Bell,
  Box,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  Edit3,
  Eye,
  Gift,
  Heart,
  LayoutDashboard,
  LogOut,
  MapPin,
  Maximize2,
  MessageCircle,
  Minus,
  Package,
  Plus,
  ReceiptText,
  Search,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Star,
  Trash2,
  Trophy,
  UserRound,
  X,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

const icons = {
  admin: ShieldCheck,
  arrowRight: ArrowRight,
  bell: Bell,
  box: Box,
  cart: ShoppingCart,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  dashboard: LayoutDashboard,
  edit: Edit3,
  eye: Eye,
  gift: Gift,
  heart: Heart,
  max: Maximize2,
  messages: MessageCircle,
  minus: Minus,
  orders: ReceiptText,
  package: Package,
  pin: MapPin,
  plus: Plus,
  search: Search,
  shield: ShieldCheck,
  shop: ShoppingBag,
  star: Star,
  trash: Trash2,
  trophy: Trophy,
  user: UserRound,
  logout: LogOut,
  x: X,
  zoom: ZoomIn,
  zoomOut: ZoomOut,
};

export function Icon({ name, className = 'h-4 w-4' }) {
  const Component = icons[name] || Package;
  return <Component aria-hidden="true" className={className} strokeWidth={1.8} />;
}
